spring:
  datasource:
    url: jdbc:mysql://localhost:3306/printermng
    username: root
    password: xgrc0295
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.printer.domain
  mapper-locations: classpath:mybatis/mapper/*.xml




